version: '3.8'
services:
  logstash-practice:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash-practice
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml

      # 다중서버 설정
      - ./pipelines/mypipe1.conf:/usr/share/logstash/config/mypipe1.conf
      - ./pipelines/mypipe2.conf:/usr/share/logstash/config/mypipe2.conf
      - ./pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml

      # 단일서버 설정
      - ./pipelines/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs
    ports:
      - "5044:5044"
      # - "5000:5000/tcp"
      # - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"

networks:
  default:
    external:
      name: logging