http.host: "0.0.0.0"
config.reload.automatic: true
xpack.monitoring.elasticsearch.hosts: [ "http://esm01:9200" ]

# log-stash monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: "logstash_system"
xpack.monitoring.elasticsearch.password: "password"
